export const MockData = [
  [
    "Staff Name",
    "Title",
    "Assigned Task",
    "Team",
    "Skills",
    "Shift Time",
    "Other Task 1",
    "Other Task 1 Time",
    "Other Task 2",
    "Other Task 2 Time",
  ],
  [
    "John Doe",
    "Developer",
    "Feature A",
    "Team A",
    "JavaScript, React",
    "9 AM - 5 PM",
    "Bug Fix",
    "1 hour",
    "Code Review",
    "30 minutes",
  ],
  [
    "Jane Smith",
    "Designer",
    "UI/UX Design",
    "Team B",
    "Photoshop, Sketch",
    "10 AM - 6 PM",
    "Prototype",
    "2 hours",
    "Feedback Session",
    "1 hour",
  ],
  [
    "Alice Johnson",
    "Project Manager",
    "Project Planning",
    "Team A",
    "Project Management",
    "9 AM - 5 PM",
    "Meeting",
    "1 hour",
    "Documentation",
    "2 hours",
  ],
  [
    "Bob Brown",
    "QA Engineer",
    "Testing",
    "Team C",
    "Selenium, JIRA",
    "10 AM - 6 PM",
    "Regression Test",
    "3 hours",
    "Bug Reporting",
    "1 hour",
  ],
  [
    "Charlie Davis",
    "Developer",
    "Feature B",
    "Team A",
    "JavaScript, Node.js",
    "9 AM - 5 PM",
    "Code Implementation",
    "4 hours",
    "Bug Fix",
    "1 hour",
  ],
  [
    "Diana Evans",
    "Designer",
    "Wireframing",
    "Team B",
    "Figma, Adobe XD",
    "10 AM - 6 PM",
    "Wireframe Creation",
    "3 hours",
    "Design Review",
    "1 hour",
  ],
  [
    "Ethan Clark",
    "Developer",
    "Feature C",
    "Team C",
    "React, TypeScript",
    "11 AM - 7 PM",
    "API Integration",
    "4 hours",
    "Code Review",
    "1 hour",
  ],
  [
    "Fiona Green",
    "Project Coordinator",
    "Resource Allocation",
    "Team A",
    "Project Coordination",
    "9 AM - 5 PM",
    "Team Meeting",
    "1 hour",
    "Task Assignment",
    "2 hours",
  ],
  [
    "George Harris",
    "QA Lead",
    "Test Strategy",
    "Team B",
    "Automation Testing",
    "10 AM - 6 PM",
    "Test Planning",
    "2 hours",
    "Test Execution",
    "3 hours",
  ],
  [
    "Hannah Lee",
    "Developer",
    "Bug Fixes",
    "Team C",
    "JavaScript, Python",
    "11 AM - 7 PM",
    "Debugging",
    "3 hours",
    "Code Refactoring",
    "2 hours",
  ],
  [
    "Ivy King",
    "UI Designer",
    "Interface Design",
    "Team A",
    "Sketch, Figma",
    "10 AM - 6 PM",
    "Design Mockups",
    "3 hours",
    "Client Feedback",
    "1 hour",
  ],
  [
    "Jack Lewis",
    "Developer",
    "Feature D",
    "Team B",
    "React, Node.js",
    "9 AM - 5 PM",
    "Feature Development",
    "5 hours",
    "Code Review",
    "2 hours",
  ],
  [
    "Katherine Martinez",
    "Business Analyst",
    "Requirement Gathering",
    "Team C",
    "Business Analysis",
    "10 AM - 6 PM",
    "Stakeholder Meeting",
    "1 hour",
    "Requirement Documentation",
    "2 hours",
  ],
  [
    "Liam Moore",
    "DevOps Engineer",
    "CI/CD Pipeline",
    "Team A",
    "Docker, Jenkins",
    "9 AM - 5 PM",
    "Pipeline Setup",
    "3 hours",
    "Deployment",
    "2 hours",
  ],
  [
    "Mia Nelson",
    "Content Writer",
    "Content Creation",
    "Team B",
    "Writing, Editing",
    "10 AM - 6 PM",
    "Article Writing",
    "4 hours",
    "Content Review",
    "1 hour",
  ],
  [
    "Noah Owens",
    "Database Administrator",
    "Database Maintenance",
    "Team C",
    "SQL, PostgreSQL",
    "11 AM - 7 PM",
    "Database Backup",
    "2 hours",
    "Performance Tuning",
    "3 hours",
  ],
  [
    "Olivia Parker",
    "Product Manager",
    "Product Roadmap",
    "Team A",
    "Product Management",
    "9 AM - 5 PM",
    "Roadmap Planning",
    "2 hours",
    "Feature Prioritization",
    "2 hours",
  ],
  [
    "Paul Quinton",
    "Frontend Developer",
    "UI Implementation",
    "Team B",
    "HTML, CSS",
    "10 AM - 6 PM",
    "UI Development",
    "4 hours",
    "Integration Testing",
    "1 hour",
  ],
  [
    "Quinn Roberts",
    "Backend Developer",
    "API Development",
    "Team C",
    "Node.js, Express",
    "11 AM - 7 PM",
    "API Coding",
    "5 hours",
    "Unit Testing",
    "2 hours",
  ],
  [
    "Rachel Stewart",
    "Designer",
    "Graphic Design",
    "Team A",
    "Illustrator, InDesign",
    "10 AM - 6 PM",
    "Graphic Creation",
    "3 hours",
    "Design Approval",
    "1 hour",
  ],
  [
    "Sam Thomas",
    "Scrum Master",
    "Scrum Meetings",
    "Team B",
    "Agile, Scrum",
    "9 AM - 5 PM",
    "Daily Standup",
    "1 hour",
    "Sprint Planning",
    "2 hours",
  ],
  [
    "Tina Underwood",
    "SEO Specialist",
    "SEO Optimization",
    "Team C",
    "SEO Tools",
    "10 AM - 6 PM",
    "Keyword Research",
    "2 hours",
    "SEO Strategy",
    "3 hours",
  ],
  [
    "Ulysses Vance",
    "Support Specialist",
    "Customer Support",
    "Team A",
    "Customer Service",
    "9 AM - 5 PM",
    "Support Tickets",
    "4 hours",
    "Customer Follow-up",
    "2 hours",
  ],
  [
    "Vera Walker",
    "Systems Analyst",
    "System Analysis",
    "Team B",
    "System Analysis",
    "10 AM - 6 PM",
    "System Design",
    "3 hours",
    "Requirements Gathering",
    "2 hours",
  ],
  [
    "William Xu",
    "Web Developer",
    "Website Maintenance",
    "Team C",
    "JavaScript, PHP",
    "11 AM - 7 PM",
    "Site Updates",
    "4 hours",
    "Bug Fixes",
    "2 hours",
  ],
  [
    "Xena Young",
    "Marketing Manager",
    "Campaign Management",
    "Team A",
    "Marketing Tools",
    "9 AM - 5 PM",
    "Campaign Planning",
    "3 hours",
    "Performance Analysis",
    "2 hours",
  ],
  [
    "Yara Zane",
    "Financial Analyst",
    "Financial Reporting",
    "Team B",
    "Excel, QuickBooks",
    "10 AM - 6 PM",
    "Report Generation",
    "3 hours",
    "Data Analysis",
    "2 hours",
  ],
  [
    "Zane Adams",
    "HR Manager",
    "Recruitment",
    "Team C",
    "HR Management",
    "11 AM - 7 PM",
    "Interview Scheduling",
    "2 hours",
    "Candidate Evaluation",
    "2 hours",
  ],
  [
    "Anna Brooks",
    "Content Strategist",
    "Content Strategy",
    "Team A",
    "Content Planning",
    "9 AM - 5 PM",
    "Strategy Development",
    "4 hours",
    "Content Review",
    "2 hours",
  ],
  [
    "Ben Carter",
    "Network Engineer",
    "Network Maintenance",
    "Team B",
    "Networking",
    "10 AM - 6 PM",
    "Network Setup",
    "3 hours",
    "Troubleshooting",
    "2 hours",
  ],
  [
    "Clara Dawson",
    "Legal Advisor",
    "Contract Review",
    "Team C",
    "Legal Compliance",
    "11 AM - 7 PM",
    "Contract Drafting",
    "2 hours",
    "Legal Consultation",
    "3 hours",
  ],
  [
    "David Edwards",
    "Sales Executive",
    "Sales Strategy",
    "Team A",
    "Sales Tools",
    "9 AM - 5 PM",
    "Sales Planning",
    "3 hours",
    "Client Meetings",
    "2 hours",
  ],
  [
    "Ella Foster",
    "Customer Success Manager",
    "Client Onboarding",
    "Team B",
    "Customer Success",
    "10 AM - 6 PM",
    "Onboarding Sessions",
    "2 hours",
    "Client Training",
    "3 hours",
  ],
  [
    "Freddie Grant",
    "Data Scientist",
    "Data Analysis",
    "Team C",
    "Data Tools",
    "11 AM - 7 PM",
    "Data Modeling",
    "4 hours",
    "Report Generation",
    "2 hours",
  ],
  [
    "Gina Harris",
    "Product Designer",
    "Design Implementation",
    "Team A",
    "Product Design",
    "9 AM - 5 PM",
    "Design Execution",
    "3 hours",
    "Design Iteration",
    "2 hours",
  ],
  [
    "Harry Ingram",
    "Business Development",
    "Business Growth",
    "Team B",
    "Business Development",
    "10 AM - 6 PM",
    "Growth Strategies",
    "4 hours",
    "Market Research",
    "2 hours",
  ],
  [
    "Irene Jones",
    "DevOps Specialist",
    "Infrastructure Management",
    "Team C",
    "DevOps Tools",
    "11 AM - 7 PM",
    "Infrastructure Setup",
    "3 hours",
    "Automation",
    "2 hours",
  ],
  [
    "Jake Kim",
    "Creative Director",
    "Creative Strategy",
    "Team A",
    "Creative Tools",
    "9 AM - 5 PM",
    "Strategy Planning",
    "3 hours",
    "Creative Review",
    "2 hours",
  ],
  [
    "Lily Lawrence",
    "Operations Manager",
    "Operational Efficiency",
    "Team B",
    "Operations Management",
    "10 AM - 6 PM",
    "Process Improvement",
    "3 hours",
    "Team Coordination",
    "2 hours",
  ],
  [
    "Michael Moore",
    "Security Analyst",
    "Security Management",
    "Team C",
    "Security Tools",
    "11 AM - 7 PM",
    "Security Monitoring",
    "4 hours",
    "Incident Response",
    "3 hours",
  ],
  [
    "Nina Peterson",
    "Graphic Designer",
    "Visual Design",
    "Team A",
    "Design Tools",
    "9 AM - 5 PM",
    "Visual Design",
    "3 hours",
    "Client Feedback",
    "1 hour",
  ],
  [
    "Oscar Quinn",
    "Software Engineer",
    "System Development",
    "Team B",
    "Software Development",
    "10 AM - 6 PM",
    "System Design",
    "4 hours",
    "Code Review",
    "2 hours",
  ],
  [
    "Paula Robinson",
    "UX Researcher",
    "User Research",
    "Team C",
    "Research Tools",
    "11 AM - 7 PM",
    "User Interviews",
    "3 hours",
    "Research Analysis",
    "2 hours",
  ],
];
